gradle_witness_ng_error:EEE-0001:Could not resolve all files for configuration ':app:debugAndroidTestCompileClasspath'.
gradle_witness_ng_error:EEE-0001:Could not resolve all files for configuration ':app:debugAnnotationProcessorClasspath'.
gradle_witness_ng_error:EEE-0001:Could not resolve all files for configuration ':app:debugCompileClasspath'.
gradle_witness_ng_error:EEE-0001:Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
gradle_witness_ng_error:EEE-0001:Could not resolve all files for configuration ':app:debugUnitTestCompileClasspath'.
gradle_witness_ng_error:EEE-0001:Could not resolve all files for configuration ':app:debugUnitTestRuntimeClasspath'.
gradle_witness_ng_error:EEE-0001:Could not resolve all files for configuration ':app:releaseAnnotationProcessorClasspath'.
gradle_witness_ng_error:EEE-0001:Could not resolve all files for configuration ':app:releaseCompileClasspath'.
gradle_witness_ng_error:EEE-0001:Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
gradle_witness_ng_error:EEE-0001:Could not resolve all files for configuration ':app:releaseUnitTestCompileClasspath'.
gradle_witness_ng_error:EEE-0001:Could not resolve all files for configuration ':app:releaseUnitTestRuntimeClasspath'.
dependencyVerification {
    verify = [
        'androidx.annotation:annotation-experimental:1.1.0:annotation-experimental-1.1.0.aar:0157de61a2064047896a058080f3fd67ba57ad9a94857b3f7a363660243e3f90',
        'androidx.annotation:annotation-experimental:1.4.1:annotation-experimental-1.4.1.aar:6bd4c7c7476f8260cd3bdbb81183583e93fc9f790c27dea7dc314181cbf87aa0',
        'androidx.annotation:annotation-jvm:1.9.0:annotation-jvm-1.9.0.jar:3236e1e44c41da378c1ac9b515bee0501d8dc512991465100acb4dfe64059a4e',
        'androidx.annotation:annotation:1.2.0:annotation-1.2.0.jar:9029262bddce116e6d02be499e4afdba21f24c239087b76b3b57d7e98b490a36',
        'androidx.concurrent:concurrent-futures:1.1.0:concurrent-futures-1.1.0.jar:0ce067c514a0d1049d1bebdf709e344ed3266fe9744275682937cdcb13334e9e',
        'androidx.lifecycle:lifecycle-common:2.3.1:lifecycle-common-2.3.1.jar:15848fb56db32f4c7cdc72b324003183d52a4884d6bf09be708ac7f587d139b5',
        'androidx.lifecycle:lifecycle-common:2.6.2:lifecycle-common-2.6.2.jar:f34831b6c71cd844e1d35d1be49d5e79447c5ab856346531b1e8676fda7374b1',
        'androidx.multidex:multidex-instrumentation:2.0.0:multidex-instrumentation-2.0.0.aar:fb8115694b1731c23c1bbb628f5baaee37a8f3b50d69a7733b55278e101e1488',
        'androidx.multidex:multidex:2.0.1:multidex-2.0.1.aar:42dd32ff9f97f85771b82a20003a8d70f68ab7b4ba328964312ce0732693db09',
        'androidx.test.espresso:espresso-core:3.5.1:espresso-core-3.5.1.aar:34b0493f4e002f205d961e562add0c0c31bb0acc657e89d89d4b188ac13f242c',
        'androidx.test.espresso:espresso-idling-resource:3.5.1:espresso-idling-resource-3.5.1.aar:84fb8e2f5eda937771bee28582f5d2cfa61b0e9438d02041ca61b81e3dac3c87',
        'androidx.test.espresso:espresso-intents:3.5.1:espresso-intents-3.5.1.aar:63917bce0b9050166875edb8a60904307418c0731cc2e009feb7aa8dacbd2366',
        'androidx.test.ext:junit:1.1.5:junit-1.1.5.aar:4307c0e60f5d701db9c59bcd9115af705113c36a9132fa3dbad58db1294e9bfd',
        'androidx.test.ext:truth:1.5.0:truth-1.5.0.aar:fe65b8920081434c57c9c1578d2c43b04b64154f3691c4c092106c7dc3160ac1',
        'androidx.test.services:storage:1.4.2:storage-1.4.2.aar:b34861f0cd920cb1089f08c3f27e5865b7f920284cc45f4ed12ef8d6980dac48',
        'androidx.test.services:test-services:1.5.0:test-services-1.5.0.apk:69893d87f3682a2abf95757bfa57c062a491d34f316cb55dc99a022e9c1dbbbe',
        'androidx.test:annotation:1.0.1:annotation-1.0.1.aar:c0754928effe1968c3a9a7b55d1dfc7ceb1e1e7c9f3f09f98afd42431f712492',
        'androidx.test:core:1.5.0:core-1.5.0.aar:2c06715c0d0843cee2143ab8bb322bb3f34d5247630402fc8c1b6a0eafa15b9f',
        'androidx.test:monitor:1.6.1:monitor-1.6.1.aar:2985ce8556989baf7c84342e7f687713c037a39a922e614d1a3ddf1ca3777079',
        'androidx.test:rules:1.5.0:rules-1.5.0.aar:dd645929c63e24f41be8e6f57bb06f305d3b02ed1b2a7d961647027ae1d9e17f',
        'androidx.test:runner:1.5.2:runner-1.5.2.aar:36cd6bc876daa1f183ccd11f9898e094c71f06960fde85a373422959613a44d6',
        'androidx.tracing:tracing:1.0.0:tracing-1.0.0.aar:07b8b6139665b884a162eccf97891ca50f7f56831233bf25168ae04f7b568612',
        'com.almworks.sqlite4java:sqlite4java:1.0.392:sqlite4java-1.0.392.jar:243a64470fda0e86a6fddeb0af4c7aa9426ce84e68cbfe18d75ee5da4b7e0b92',
        'com.android.tools.ddms:ddmlib:31.6.0:ddmlib-31.6.0.jar:c571c0224fe3e7e6607196d95cc3142fdc19f013e8f1510f68c7b4a686c53809',
        'com.android.tools.emulator:proto:31.6.0:proto-31.6.0.jar:5994f35bcfe498aee92a82340b7600902439b1aa153b9398591105c4e00bb994',
        'com.android.tools.utp:android-device-provider-ddmlib-proto:31.6.0:android-device-provider-ddmlib-proto-31.6.0.jar:da9f3f3dae26544c90668549584765d5854a87c425d2cfe577cd34d3600ea097',
        'com.android.tools.utp:android-device-provider-ddmlib:31.6.0:android-device-provider-ddmlib-31.6.0.jar:2c32f1a43eed32f81c060347a880e8f5fd7a76e28ffe4ca99a60da047090fe46',
        'com.android.tools.utp:android-device-provider-gradle-proto:31.6.0:android-device-provider-gradle-proto-31.6.0.jar:ad2342bb1d6f95563400a322493ea1c229cb93df3944f1261b7399f718494049',
        'com.android.tools.utp:android-device-provider-gradle:31.6.0:android-device-provider-gradle-31.6.0.jar:02a69cb13054e7b120961f41a9d91475b525a687f8169b54494320ce255c52ff',
        'com.android.tools.utp:android-test-plugin-host-additional-test-output-proto:31.6.0:android-test-plugin-host-additional-test-output-proto-31.6.0.jar:38450694de6328c2c4cba696f9c04ecdd5ce6952355f68c3a22f9541d1d6546f',
        'com.android.tools.utp:android-test-plugin-host-additional-test-output:31.6.0:android-test-plugin-host-additional-test-output-31.6.0.jar:83512570f412db55e6261769e36b0fd170d7aa9fd4c2a03044eaa97a6ff3454f',
        'com.android.tools.utp:android-test-plugin-host-apk-installer-proto:31.6.0:android-test-plugin-host-apk-installer-proto-31.6.0.jar:543eb6c8d72b2ed7451f8e939d5d80890566f14bc26b7df9c8347506b258d7ae',
        'com.android.tools.utp:android-test-plugin-host-apk-installer:31.6.0:android-test-plugin-host-apk-installer-31.6.0.jar:c4708eb0349d2ba70377d919d644202e9549f5d590cc0b1aeb71599315dd8dfd',
        'com.android.tools.utp:android-test-plugin-host-coverage-proto:31.6.0:android-test-plugin-host-coverage-proto-31.6.0.jar:efb4d7014aaa7355246a07c2e437a2231fb252540ff1bce6872c88dc8da89d12',
        'com.android.tools.utp:android-test-plugin-host-coverage:31.6.0:android-test-plugin-host-coverage-31.6.0.jar:838309dd8950b2a8e8f9f5f4e1aa96bb2cbd3af8291036b6c2618bae6100a711',
        'com.android.tools.utp:android-test-plugin-host-device-info-proto:31.6.0:android-test-plugin-host-device-info-proto-31.6.0.jar:4f5eccc1d47a981b3ff120e98a3de0988214108fe9dc7b068e95a6b686ada495',
        'com.android.tools.utp:android-test-plugin-host-device-info:31.6.0:android-test-plugin-host-device-info-31.6.0.jar:50429a9d8e7051c2006038359b921dbb188d88b2318c6f643347bafab38e49b1',
        'com.android.tools.utp:android-test-plugin-host-emulator-control-proto:31.6.0:android-test-plugin-host-emulator-control-proto-31.6.0.jar:aedec5ec4627d898cccdf42d8038db20eba4495753c53d1b0b378734491caf5f',
        'com.android.tools.utp:android-test-plugin-host-emulator-control:31.6.0:android-test-plugin-host-emulator-control-31.6.0.jar:fc1d7c8696390242cca93ec24494938542fe82eee75ce57046db46ead594b963',
        'com.android.tools.utp:android-test-plugin-host-logcat-proto:31.6.0:android-test-plugin-host-logcat-proto-31.6.0.jar:9129024bd8e38353bca3eb26dfd8e3628e058d57d6e9d8451ffc35f016751e63',
        'com.android.tools.utp:android-test-plugin-host-logcat:31.6.0:android-test-plugin-host-logcat-31.6.0.jar:48e77d757aaeb4193b8702bd0e04081a77258f7212c6688a2181111179239ab9',
        'com.android.tools.utp:android-test-plugin-host-retention-proto:31.6.0:android-test-plugin-host-retention-proto-31.6.0.jar:3db8ed38ef49b694caea466ae22e3b36cedc9557b3589d0e07c0cdd83294591c',
        'com.android.tools.utp:android-test-plugin-host-retention:31.6.0:android-test-plugin-host-retention-31.6.0.jar:b55c2fe56f5ecde208fb132680df732e6526b953958993f39d07c83a8d980d17',
        'com.android.tools.utp:android-test-plugin-result-listener-gradle-proto:31.6.0:android-test-plugin-result-listener-gradle-proto-31.6.0.jar:cbdf71bca60e14c30e7b2cf4b90f0f0a3e8c138f7cadd874b0d9c0ae082e0274',
        'com.android.tools.utp:android-test-plugin-result-listener-gradle:31.6.0:android-test-plugin-result-listener-gradle-31.6.0.jar:311c974300e3480acc21c81c19f50ddf4c73b1f20cacc194a6048a110f080202',
        'com.android.tools.utp:utp-common:31.6.0:utp-common-31.6.0.jar:595702fb80bcd4373a1b9b438e5977687cba3c5fba6fa1a2936beef79b13ee9d',
        'com.android.tools:annotations:31.6.0:annotations-31.6.0.jar:b25995fa7b220d35fbb8e325df071f8291691bfbaff9734c98e38f45ec2a73ee',
        'com.android.tools:common:31.6.0:common-31.6.0.jar:9a73761122b6d08250b26f641df2d47dcd82c293b5f6c8e4ee5bb6ef85d1b2c8',
        'com.android.tools:desugar_jdk_libs:2.1.4:desugar_jdk_libs-2.1.4.jar:d7604feeef3a771d5d616b68fcc2c42f516243311ea286cfd41e1962829a6d28',
        'com.android.tools:desugar_jdk_libs_configuration:2.1.4:desugar_jdk_libs_configuration-2.1.4.jar:5d770c1ba225c2cdf09086bf662954ae765ee481f901b02cd7b1dc3c8077c3f4',
        'com.google.android:annotations:4.1.1.4:annotations-4.1.1.4.jar:ba734e1e84c09d615af6a09d33034b4f0442f8772dec120efb376d86a565ae15',
        'com.google.api.grpc:proto-google-common-protos:2.17.0:proto-google-common-protos-2.17.0.jar:4ef1fe0c327fc1521d1d753b0b1c4a875a54bd14ebded3afff0ca395320b6ea9',
        'com.google.auto.value:auto-value-annotations:1.10.4:auto-value-annotations-1.10.4.jar:e1c45e6beadaef9797cb0d9afd5a45621ad061cd8632012f85582853a3887825',
        'com.google.code.findbugs:jsr305:2.0.2:jsr305-2.0.2.jar:1e7f53fa5b8b5c807e986ba335665da03f18d660802d8bf061823089d1bee468',
        'com.google.code.findbugs:jsr305:3.0.2:jsr305-3.0.2.jar:766ad2a0783f2687962c8ad74ceecc38a28b9f72a2d085ee438b7813e928d0c7',
        'com.google.code.gson:gson:2.10.1:gson-2.10.1.jar:4241c14a7727c34feea6507ec801318a3d4a90f070e4525681079fb94ee4c593',
        'com.google.crypto.tink:tink:1.7.0:tink-1.7.0.jar:88970a456a08ba4c66b01b23e5846ca1095cc14e54cb48363e5d2e15a1307308',
        'com.google.errorprone:error_prone_annotations:2.11.0:error_prone_annotations-2.11.0.jar:721cb91842b46fa056847d104d5225c8b8e1e8b62263b993051e1e5a0137b7ec',
        'com.google.errorprone:error_prone_annotations:2.18.0:error_prone_annotations-2.18.0.jar:9e6814cb71816988a4fd1b07a993a8f21bb7058d522c162b1de849e19bea54ae',
        'com.google.guava:failureaccess:1.0.1:failureaccess-1.0.1.jar:a171ee4c734dd2da837e4b16be9df4661afab72a41adaf31eb84dfdaf936ca26',
        'com.google.guava:guava:31.1-jre:guava-31.1-jre.jar:a42edc9cab792e39fe39bb94f3fca655ed157ff87a8af78e1d6ba5b07c4a00ab',
        'com.google.guava:guava:32.0.1-jre:guava-32.0.1-jre.jar:bd7fa227591fb8509677d0d1122cf95158f3b8a9f45653f58281d879f6dc48c5',
        'com.google.guava:listenablefuture:1.0:listenablefuture-1.0.jar:e4ad7607e5c0477c6f890ef26a49cb8d1bb4dffb650bab4502afee64644e3069',
        'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava:listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:b372a037d4230aa57fbeffdef30fd6123f9c0c2db85d0aced00c91b974f33f99',
        'com.google.j2objc:j2objc-annotations:1.3:j2objc-annotations-1.3.jar:21af30c92267bd6122c0e0b4d20cccb6641a37eaf956c6540ec471d584e64a7b',
        'com.google.j2objc:j2objc-annotations:2.8:j2objc-annotations-2.8.jar:f02a95fa1a5e95edb3ed859fd0fb7df709d121a35290eff8b74dce2ab7f4d6ed',
        'com.google.protobuf:protobuf-java:3.22.3:protobuf-java-3.22.3.jar:59d388ea6a2d2d76ae8efff7fd4d0c60c6f0f464c3d3ab9be8e5add092975708',
        'com.google.testing.platform:android-device-provider-local:0.0.9-alpha02:android-device-provider-local-0.0.9-alpha02.jar:446d0fca4e3711e3e37219cf888ec12b4dec3f14999ee439735385fb787e914b',
        'com.google.testing.platform:android-driver-instrumentation:0.0.9-alpha02:android-driver-instrumentation-0.0.9-alpha02.jar:a34731dc23ead15144ad100efac5726a7ed82c2ec8b889504d549ae72dff5029',
        'com.google.testing.platform:android-test-plugin:0.0.9-alpha02:android-test-plugin-0.0.9-alpha02.jar:a87ed1c766c9a498cfc9280ca65d0c4853875b7ed7fa5ffd89428904eba1c0ff',
        'com.google.testing.platform:core-proto:0.0.9-alpha02:core-proto-0.0.9-alpha02.jar:6d8a8906774150f43a8fad08ca64e25c6070c39bd8a6fc13b2593f289242fe95',
        'com.google.testing.platform:core:0.0.9-alpha02:core-0.0.9-alpha02.jar:fe215abd101f29fb388535592e1f14bb4cf8501da6db84422ba1945ac4e26872',
        'com.google.testing.platform:launcher:0.0.9-alpha02:launcher-0.0.9-alpha02.jar:5423e8ca410fcdbcfb3286c18b8be080eaf4ee9bd796ead903e8c885ead16ec3',
        'com.google.truth:truth:1.1.3:truth-1.1.3.jar:fc0b67782289a2aabfddfdf99eff1dcd5edc890d49143fcd489214b107b8f4f3',
        'com.ibm.icu:icu4j:74.2:icu4j-74.2.jar:95c055080e14c093ebeeba5b733e1a1be7a4af5854668c774cedf070d4240e43',
        'com.squareup:javawriter:2.1.1:javawriter-2.1.1.jar:f699823d0081f69cbb676c1845ea222e0ada79bc88a53e5d22d8bd02d328f57e',
        'commons-io:commons-io:2.13.0:commons-io-2.13.0.jar:671eaa39688dac2ffaa4645b3c9980ae2d0ea2471e4ae6a5da199cd15ae23666',
        'io.grpc:grpc-api:1.57.0:grpc-api-1.57.0.jar:8d2c384299f84ee8aa7f670f00e7cb26b87e231cf3091474307b32b76910f71c',
        'io.grpc:grpc-context:1.57.0:grpc-context-1.57.0.jar:953fcacd82f531e69b76e3834f5830bad4c22ae84144e058d71dc80a7430275d',
        'io.grpc:grpc-core:1.57.0:grpc-core-1.57.0.jar:3bee48c73bc4c5b55bed79be0e484adf26ba56bebbe5798ddbf34714ef1e1cea',
        'io.grpc:grpc-netty:1.57.0:grpc-netty-1.57.0.jar:81d43f2d4ed18fa341bd840a3735f1403a70074a046e157e27f679b721b4c9ad',
        'io.grpc:grpc-protobuf-lite:1.57.0:grpc-protobuf-lite-1.57.0.jar:2c507c02d981b84a21763d44e09af4f279881dd3e25be3080f6361258607f198',
        'io.grpc:grpc-protobuf:1.57.0:grpc-protobuf-1.57.0.jar:49f986d4eab12610fdba4a6890fca52d5eb653598916fdb863a366d5e28eecf7',
        'io.grpc:grpc-stub:1.57.0:grpc-stub-1.57.0.jar:6e6ee141539fa14d9fa479f7f511605544443c7e011e78e273cf9468aa183060',
        'io.netty:netty-buffer:4.1.93.Final:netty-buffer-4.1.93.Final.jar:007c7d9c378df02d390567d0d7ddf542ffddb021b7313dbf502392113ffabb08',
        'io.netty:netty-codec-http2:4.1.93.Final:netty-codec-http2-4.1.93.Final.jar:d96cc09045a1341c6d47494352aa263b87b72fb1d2ea9eca161aa73820bfe8bb',
        'io.netty:netty-codec-http:4.1.93.Final:netty-codec-http-4.1.93.Final.jar:dacf78ce78ab2d29570325db4cd2451ea589639807de95881a0fa7155a9e6b55',
        'io.netty:netty-codec-socks:4.1.93.Final:netty-codec-socks-4.1.93.Final.jar:0ea47b5ba23ca1da8eb9146c8fc755c1271414633b1e2be2ce1df764ba0fff2a',
        'io.netty:netty-codec:4.1.93.Final:netty-codec-4.1.93.Final.jar:990c378168dc6364c6ff569701f4f2f122fffe8998b3e189eba4c4d868ed1084',
        'io.netty:netty-common:4.1.93.Final:netty-common-4.1.93.Final.jar:443bb316599fb16e3baeba2fb58881814d7ff0b7af176fe76e38071a6e86f8c0',
        'io.netty:netty-handler-proxy:4.1.93.Final:netty-handler-proxy-4.1.93.Final.jar:2ac5f7fbefa0b73ef783889069344d5515505a14b2303be693c5002c486df2b4',
        'io.netty:netty-handler:4.1.93.Final:netty-handler-4.1.93.Final.jar:4e5f563ae14ed713381816d582f5fcfd0615aefb29203486cdfb782d8a00a02b',
        'io.netty:netty-resolver:4.1.93.Final:netty-resolver-4.1.93.Final.jar:e59770b66e81822e5d111ac4e544d7eb0c543e0a285f52628e53941acd8ed759',
        'io.netty:netty-transport-native-unix-common:4.1.93.Final:netty-transport-native-unix-common-4.1.93.Final.jar:774165a1c4dbaacb17f9c1ad666b3569a6a59715ae828e7c3d47703f479a53e7',
        'io.netty:netty-transport:4.1.93.Final:netty-transport-4.1.93.Final.jar:a5a78019bc1cd43dbc3c7b7cdd3801912ca26d1f498fb560514fee497864ba96',
        'io.perfmark:perfmark-api:0.26.0:perfmark-api-0.26.0.jar:b7d23e93a34537ce332708269a0d1404788a5b5e1949e82f5535fce51b3ea95b',
        'javax.annotation:javax.annotation-api:1.3.2:javax.annotation-api-1.3.2.jar:e04ba5195bcd555dc95650f7cc614d151e4bcd52d29a10b8aa2197f3ab89ab9b',
        'javax.inject:javax.inject:1:javax.inject-1.jar:91c77044a50c481636c32d916fd89c9118a72195390452c81065080f957de7ff',
        'junit:junit:4.13.2:junit-4.13.2.jar:8e495b634469d64fb8acfa3495a065cbacc8a0fff55ce1e31007be4c16dc57d3',
        'net.java.dev.jna:jna-platform:5.6.0:jna-platform-5.6.0.jar:9ecea8bf2b1b39963939d18b70464eef60c508fed8820f9dcaba0c35518eabf7',
        'net.java.dev.jna:jna:5.6.0:jna-5.6.0.jar:5557e235a8aa2f9766d5dc609d67948f2a8832c2d796cea9ef1d6cbe0b3b7eaf',
        'net.sf.kxml:kxml2:2.3.0:kxml2-2.3.0.jar:f264dd9f79a1fde10ce5ecc53221eff24be4c9331c830b7d52f2f08a7b633de2',
        'org.bouncycastle:bcprov-jdk18on:1.77:bcprov-jdk18on-1.77.jar:dabb98c24d72c9b9f585633d1df9c5cd58d9ad373d0cd681367e6a603a495d58',
        'org.checkerframework:checker-qual:3.13.0:checker-qual-3.13.0.jar:3ea0dcd73b4d6cb2fb34bd7ed4dad6db327a01ebad7db05eb7894076b3d64491',
        'org.checkerframework:checker-qual:3.33.0:checker-qual-3.33.0.jar:e316255bbfcd9fe50d165314b85abb2b33cb2a66a93c491db648e498a82c2de1',
        'org.codehaus.mojo:animal-sniffer-annotations:1.23:animal-sniffer-annotations-1.23.jar:9ffe526bf43a6348e9d8b33b9cd6f580a7f5eed0cf055913007eda263de974d0',
        'org.hamcrest:hamcrest-core:1.3:hamcrest-core-1.3.jar:66fdef91e9739348df7a096aa384a5685f4e875584cce89386a7a47251c4d8e9',
        'org.hamcrest:hamcrest-integration:1.3:hamcrest-integration-1.3.jar:70f418efbb506c5155da5f9a5a33262ea08a9e4d7fea186aa9015c41a7224ac2',
        'org.hamcrest:hamcrest-library:1.3:hamcrest-library-1.3.jar:711d64522f9ec410983bd310934296da134be4254a125080a0416ec178dfad1c',
        'org.jetbrains.intellij.deps:trove4j:1.0.20200330:trove4j-1.0.20200330.jar:c5fd725bffab51846bf3c77db1383c60aaaebfe1b7fe2f00d23fe1b7df0a439d',
        'org.jetbrains.kotlin:kotlin-build-tools-api:2.1.20:kotlin-build-tools-api-2.1.20.jar:533c36cb362e6ed2d15f58732e7f4c6d2bed5c9d5179b897bc4b09d16d605377',
        'org.jetbrains.kotlin:kotlin-build-tools-impl:2.1.20:kotlin-build-tools-impl-2.1.20.jar:6e94896e321603e3bfe89fef02478e44d1d64a3d25d49d0694892ffc01c60acf',
        'org.jetbrains.kotlin:kotlin-compiler-embeddable:2.1.20:kotlin-compiler-embeddable-2.1.20.jar:c54a00718c8c0e3ee858bf42771c7f401c5e3c1738861e18e9536371042fa1b3',
        'org.jetbrains.kotlin:kotlin-compiler-runner:2.1.20:kotlin-compiler-runner-2.1.20.jar:de3b5423d8fbf86ea2bd1334d401bc4aa84e28ec48945952d11c00b10b1402b6',
        'org.jetbrains.kotlin:kotlin-daemon-client:2.1.20:kotlin-daemon-client-2.1.20.jar:3630a30182c63570eb519ae65aaa9419217dbad0814fede42c8dde704465a4c6',
        'org.jetbrains.kotlin:kotlin-daemon-embeddable:2.1.20:kotlin-daemon-embeddable-2.1.20.jar:d9e83df1d847a201ba3c016a786ced091be9503997d09f6a9cf1796ee489f374',
        'org.jetbrains.kotlin:kotlin-klib-commonizer-embeddable:2.1.20:kotlin-klib-commonizer-embeddable-2.1.20.jar:4d13fee05bbb471942c3b5ede0f28aba2e011960e6412674b8287bad866e2dfa',
        'org.jetbrains.kotlin:kotlin-reflect:1.6.10:kotlin-reflect-1.6.10.jar:3277ac102ae17aad10a55abec75ff5696c8d109790396434b496e75087854203',
        'org.jetbrains.kotlin:kotlin-script-runtime:2.1.20:kotlin-script-runtime-2.1.20.jar:ae4397fbb3aa2a1ada09290e753bba99a4114548977c3115526b9958f4cb1a04',
        'org.jetbrains.kotlin:kotlin-scripting-common:2.1.20:kotlin-scripting-common-2.1.20.jar:5fdbf6ae72237ce335d603eb12c49b09bc9c1a33c0c01f1d62e77ff33663cefb',
        'org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:2.1.20:kotlin-scripting-compiler-embeddable-2.1.20.jar:3d4f772b238414650017e97462256b7c4d5edfa1013cbf5477573eb1ac2e2884',
        'org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable:2.1.20:kotlin-scripting-compiler-impl-embeddable-2.1.20.jar:f665d70b1a0837ff3a0ef7bec4fc5d9fed67ea75e4697de158eb51f1ea501c3f',
        'org.jetbrains.kotlin:kotlin-scripting-jvm:2.1.20:kotlin-scripting-jvm-2.1.20.jar:69f457acab98364c0eb578c497e0c3ca930b8cfb82be774049da04cde38087f7',
        'org.jetbrains.kotlin:kotlin-stdlib-common:1.7.10:kotlin-stdlib-common-1.7.10.jar:19f102efe9629f8eabc63853ad15c533e47c47f91fca09285c5bde86e59f91d4',
        'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.20:kotlin-stdlib-jdk7-1.9.20.jar:c5451d67a27f33afd09913c67e1ceba3897ae70884b24ef0ff71157e55b60865',
        'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.20:kotlin-stdlib-jdk8-1.9.20.jar:f833fcc94f0bb1c31b9e78bd4bda7ea23f579ff3408ae1a94e2eb5747086a2ab',
        'org.jetbrains.kotlin:kotlin-stdlib:1.7.10:kotlin-stdlib-1.7.10.jar:e771fe74250a943e8f6346713201ff1d8cb95c3a5d1a91a22b65a9e04f6a8901',
        'org.jetbrains.kotlin:kotlin-stdlib:1.9.20:kotlin-stdlib-1.9.20.jar:28a35bcdff46d864f80f346a617e486284b208d17378c41900dfb1de95a90e6c',
        'org.jetbrains.kotlin:kotlin-stdlib:2.1.20:kotlin-stdlib-2.1.20-all.jar:81e07de34e84b29e14f3fdef902f4bc4cf1d5da959b867df683fbe1cc54ce1e1',
        'org.jetbrains.kotlin:kotlin-stdlib:2.1.20:kotlin-stdlib-2.1.20.jar:1bcc74e8ce84e2c25eaafde10f1248349cce3062b6e36978cbeec610db1e930a',
        'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4:kotlinx-coroutines-android-1.6.4.jar:3fdc0eed5bc4b83ee9622774520a2db25470370eacd1581cac1e37704f095b00',
        'org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4:kotlinx-coroutines-core-jvm-1.6.4.jar:c24c8bb27bb320c4a93871501a7e5e0c61607638907b197aef675513d4c820be',
        'org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.8.0:kotlinx-coroutines-core-jvm-1.8.0.jar:9860906a1937490bf5f3b06d2f0e10ef451e65b95b269f22daf68a3d1f5065c5',
        'org.jetbrains:annotations:13.0:annotations-13.0.jar:ace2a10dc8e2d5fd34925ecac03e4988b2c0f851650c94b8cef49ba1bd111478',
        'org.jetbrains:annotations:23.0.0:annotations-23.0.0.jar:7b0f19724082cbfcbc66e5abea2b9bc92cf08a1ea11e191933ed43801eb3cd05',
        'org.ow2.asm:asm-analysis:9.7:asm-analysis-9.7.jar:7bc6bcbc21379948a0c8c467fb0f864206e5b818f6bc0b546872f5c9f941556f',
        'org.ow2.asm:asm-commons:9.7:asm-commons-9.7.jar:389bc247958e049fc9a0408d398c92c6d370c18035120395d4cba1d9d9304b7a',
        'org.ow2.asm:asm-tree:9.7:asm-tree-9.7.jar:62f4b3bc436045c1acb5c3ba2d8ec556ec3369093d7f5d06c747eb04b56d52b1',
        'org.ow2.asm:asm-util:9.7:asm-util-9.7.jar:37a6414d36641973f1af104937c95d6d921b2ddb4d612c66c5a9f2b13fc14211',
        'org.ow2.asm:asm:9.7:asm-9.7.jar:adf46d5e34940bdf148ecdd26a9ee8eea94496a72034ff7141066b3eea5c4e9d',
        'org.robolectric:annotations:4.12.2:annotations-4.12.2.jar:329ce893a1b3e96c06ee75d07b9b9f99ecf6389acb5c0d17fcb9d25350db0a7a',
        'org.robolectric:junit:4.12.2:junit-4.12.2.jar:f3f6ebf476b4ecdffcfe4e8b3b3d6119cbe2fc59f19822d8a6c7df35dbf22c48',
        'org.robolectric:nativeruntime:4.12.2:nativeruntime-4.12.2.jar:f8e55ab954404735f5931b5179e139e158367139b7deeddf6ded7086a0467d9d',
        'org.robolectric:pluginapi:4.12.2:pluginapi-4.12.2.jar:822af3ccba184421c36684ec4678e1b1b4424520891d46b1f568c10d3b036ba5',
        'org.robolectric:plugins-maven-dependency-resolver:4.12.2:plugins-maven-dependency-resolver-4.12.2.jar:af77ec038d8c9771fed6942fc905520c80231c1aef321ede2869227e9bd8fb08',
        'org.robolectric:resources:4.12.2:resources-4.12.2.jar:7a3371613ac23070030566ac590297b301362aba8cba9372acf0f3701cfe5c99',
        'org.robolectric:robolectric:4.12.2:robolectric-4.12.2.jar:b8eb9d7cf85bb9636f430d68a50768d1a01a747c94b40b8e8a79abe6a3f95f82',
        'org.robolectric:sandbox:4.12.2:sandbox-4.12.2.jar:8f0c3966ab51d0fca1ede8a4e706440d3783dbf4f6ec5c484fd3fcf0d9b9c9bf',
        'org.robolectric:shadowapi:4.12.2:shadowapi-4.12.2.jar:1918a7cfd69f82e2f125a56fa032e3828437a941ec9f077e7a3a652e84cb5cdc',
        'org.robolectric:shadows-framework:4.12.2:shadows-framework-4.12.2.jar:907dd8bb9966ba4b83a017822449fc8ab31ab0a437b29342cb2cfca1177354e1',
        'org.robolectric:shadows-versioning:4.12.2:shadows-versioning-4.12.2.jar:86126b5b074cb69c6953666ae467de1fa3b6d33bf794633d5b80a1be97ff4b1a',
        'org.robolectric:utils-reflector:4.12.2:utils-reflector-4.12.2.jar:7e8a926d88d473a05af7cbef07941e03ddf676e987d70f40096193dba0cf5621',
        'org.robolectric:utils:4.12.2:utils-4.12.2.jar:80f49b35125981818d73b3a8df7324c08fe86a8ce4ca94b5fea324efecb034a9',
    ]
}
