#! /bin/bash

_HOME2_=$(dirname $0)
export _HOME2_
_HOME_=$(cd $_HOME2_;pwd)
export _HOME_

basedir="$_HOME_""/../"
cd "$basedir"


LDFLAGS+=("-fuse-ld=gold")
LDFLAGS+=("-Wl,--detect-odr-violations")
LDFLAGS+=("-Wl,--warn-common")
LDFLAGS+=("-Wl,--warn-execstack")
LDFLAGS+=("-Wl,-z,noexecstack")
LDFLAGS+=("-Wl,-z,now")

CPPCHECK=("--enable=all")
CPPCHECK+=("--force")
CPPCHECK+=("--inconclusive")
CPPCHECK+=("--error-exitcode=1")
#CPPCHECK+=("--suppress=allocaCalled")
#CPPCHECK+=("--suppress=knownConditionTrueFalse")
CPPCHECK+=("--suppress=missingIncludeSystem")
#CPPCHECK+=("--suppress=signConversion")
#CPPCHECK+=("--suppress=redundantAssignment")
#CPPCHECK+=("--suppress=nullPointerRedundantCheck")
#CPPCHECK+=("--suppress=AssignmentAddressToInteger")
#CPPCHECK+=("--suppress=arrayIndexOutOfBoundsCond")

#CPPCHECK_C=("--suppress=unusedFunction")

#CPPCHECK_CXX+=("--suppress=shadowArgument")
#CPPCHECK_CXX+=("--suppress=shadowFunction")
#CPPCHECK_CXX+=("--suppress=constParameter")
#CPPCHECK_CXX+=("--suppress=sizeofFunctionCall")

cppcheck "${CPPCHECK[@]}" "${CPPCHECK_CXX[@]}" ./jni-c-toxcore/jni-c-toxcore.c "${CPPFLAGS[@]}" "$@" 2>&1 |\
 grep -v -e 'The function '"'"'Java_com_zoffcc_applications_' \
 -e 'The function '"'"'AttachJava'"'"' is never used.' \
 -e 'The function '"'"'JNI_OnLoad'"'"' is never used.'


