name: Generate Changelog

on:
  release:
    types: [published, edited]
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:
  gen-changelog:
    runs-on: ubuntu-latest
    environment: genlog_gen_token_trifa
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: run github-changelog-generator
      env:
            CHANGELOG_GEN_TOKEN: ${{ secrets.CHANGELOG_GEN_TOKEN }}
      run:  |
            pwd
            docker run --rm -v "$(pwd)":/usr/local/src/your-app githubchangeloggenerator/github-changelog-generator \
            -u zoff99 -p ToxAndroidRefImpl \
            --exclude-tags "$(git tag -l 'trifajni*'| tr '\n' ',')nightly" \
               --token "$CHANGELOG_GEN_TOKEN"

    - name: chmod
      run:  |
            sudo chmod a+r /home/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/CHANGELOG.md
            ls -rattlh

    - name: upload Changelog file
      uses: actions/upload-artifact@v7
      with:
        name: Changelog
        path: |
          /home/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/CHANGELOG.md

