name: Auto update dependencies

on:
#  schedule:
#    # runs daily at 12:00 am
#    - cron: '0 0 * * *'
  push:
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy


jobs:
  auto-update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run auto dependency update
      run: ./check_ffmpeg.sh
