name: Auto update dependencies

on:
#  schedule:
#    # runs daily at 12:00 am
#    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  auto-update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run auto dependency update
      uses: romoh/dependencies-autoupdate@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        update-command: "'./check_ffmpeg.sh'"
        on-changes-command: "./done.sh"
