name: Maven Package CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install NDK
      run: |
           echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT} >/dev/null 2>/dev/null
           echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;20.1.5948944" --sdk_root=${ANDROID_SDK_ROOT} >/dev/null 2>/dev/null

    - name: pkgs
      run: |
           sudo apt update && \
           sudo DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
           clang \
           cmake \
           libconfig-dev \
           libgtest-dev \
           ninja-build \
           pkg-config \
           zip grep file ca-certificates autotools-dev autoconf automake \
           git bc wget rsync cmake make pkg-config libtool \
           ssh gzip tar \
           coreutils \
           python \
           libncurses5

    - name: move_source
      run: |
           sudo cp -av /home/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/jni-c-toxcore /root/work/

    - name: build_maven_deps
      run: |
           sudo mkdir -p ~/work/deploy
           sudo mkdir -p ~/.android/
           sudo touch ~/.android/debug.keystore
           sudo mkdir -p build_dir
           sudo mkdir -p /home/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/build_dir
           pwd
           ls -al
           sudo bash -c "export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee';cd /home/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/build_dir/;../circle_scripts/deps.sh"

    - name: build_maven_pkg
      run: |
           pwd
           sudo bash -c "export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee';cd /home/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/build_dir/;../circle_scripts/trifa.sh '../'"

    - name: upload apk
      uses: actions/upload-artifact@v1
      with:
        name: trifa
        path: /home/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/android-refimpl-app/app/build/outputs/apk/debug/app-debug.apk

